<?php
/**
 * Created by PhpStorm.
 * User: WangShiKui
 * Date: 17-11-10
 * Time: 下午2:23
 */
namespace mobileWeb\modules\web\modules\weakness;


use yii\base\Module;

class WeaknessModule extends Module
{
    public $controllerNamespace = 'mobileWeb\modules\web\modules\weakness\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}