<?php
/**
 * Created by PhpStorm.
 * User: WangShiKui
 * Date: 17-11-10
 * Time: 下午2:20
 */

namespace mobileWeb\modules\web\modules\homework;


use yii\base\Module;

class HomeworkModule extends Module
{
    public $controllerNamespace = 'mobileWeb\modules\web\modules\homework\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}