<?php
/**
 * Created by PhpStorm.
 * User: WangShiKui
 * Date: 17-11-10
 * Time: 下午3:16
 */

namespace mobileWeb\modules\web;


use yii\base\Module;

class WebModule extends Module
{
    public $controllerNamespace = 'mobileWeb\modules\web\modules';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->modules = [
            'homework' => [
                'class' => 'mobileWeb\modules\web\modules\homework\HomeworkModule',
            ],
            'weakness' => [
                'class' => 'mobileWeb\modules\web\modules\weakness\WeaknessModule'
            ]
        ];
    }

}