<?php
/**
 * Created by PhpStorm.
 * User: WangShiKui
 * Date: 17-10-12
 * Time: 上午11:50
 */

namespace mobileWeb\modules\api\modules\courseware\controllers;


use common\clients\material\ListService;
use mobileWeb\components\HttpAndCookiesBearerAuth;
use mobileWeb\controllers\RestfulBaseController;


class MaterialCollectController extends RestfulBaseController
{
    public function behaviors()
    {
        $arr1 = parent::behaviors(); // TODO: Change the autogenerated stub
        $arr2 = [
            'authenticator' => [
                'class' => HttpAndCookiesBearerAuth::className(),

            ]
        ];

        return array_merge($arr1,$arr2);
    }

    /**
     * 获取我收藏的课件教案列表
     * @return array
     */
    public function actionIndex()
    {
        $userId = user()->id;
        $perPage = app()->request->get('per-page', 10);
        $page = app()->request->get('page', 1);
        $listService = new ListService();
        $userCollectResult = $listService->userCollectList($perPage,$page,$userId);

        $userCollectList = array();
        $userCollectList['items'] = array();

        $pageInfo = new \stdClass();
        $pageInfo->totalCount=0;
        $pageInfo->pageCount=0;
        $pageInfo->currentPage=$page;
        $pageInfo->perPage = $perPage;


        if ($userCollectResult->code==200){
            $userCollectListInfo = $userCollectResult->body;
            $pageInfo->pageCount = $userCollectListInfo->pageCount;
            $pageInfo->totalCount = $userCollectListInfo->totalCount;
            $userCollectList['items'] = $userCollectListInfo->data;

        }
        $userCollectList['_meta'] = $pageInfo;
        return $userCollectList;
    }


}