<?php
namespace mobileWeb\modules\api\modules\courseware\controllers;
use mobileWeb\components\HttpAndCookiesBearerAuth;
use mobileWeb\controllers\RestfulBaseController;
use stdClass;

/**
 * Created by PhpStorm.
 * User: liuxing
 * Date: 17-12-5
 * Time: 下午5:34
 */
class UserController extends RestfulBaseController
{
    public function behaviors()
    {
        $arr1 = parent::behaviors(); // TODO: Change the autogenerated stub
        $arr2 = [
            'authenticator' => [
                'class' => HttpAndCookiesBearerAuth::className(),

            ]
        ];

        return array_merge($arr1, $arr2);
    }

    /**
     * 返回当前登录用户的等级
     * @return stdClass
     */
    public function actionUserLevel()
    {
        $userLevel = (int)loginUser()->memberLevel;
        $userLevelObj = new \stdClass();
        $userLevelObj->memberLevel = $userLevel;
        return $userLevelObj;

    }
}