<?php
/**
 * Created by PhpStorm.
 * User: WangShiKui
 * Date: 17-10-12
 * Time: 下午6:02
 */

namespace mobileWeb\modules\api\modules\homework;


use yii\base\Module;

class HomeworkModule extends Module
{
    public $controllerNamespace = 'mobileWeb\modules\api\modules\homework\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}