<?php
return [
    'adminEmail' => 'admin@example.com',
    'nep_webService' => 'http://192.168.1.23:9098/',
    'homework_webService' => 'http://192.168.1.33:9050/',
    'pos_webService' => 'http://192.168.1.23:9098/posidon/',
    'apollo_webService' => 'http://192.168.1.23:9098/',
    'keyWords_Service' => 'http://192.168.1.45:8016',
    'banhai_webService' => 'http://192.168.1.23:3001',
    'picFit' => '//c02.banhai.com/picfit/',
    'picFitKey' => 'who',
    'traceLogUrl' => [
        ['name' => 'platform/video/index', 'p' => 'video'],
        ['name' => 'platform/video/list', 'p' => 'video'],
        ['name' => 'platform/video/detail', 'p' => 'video'],
        ['name' => 'platform/file', 'p' => 'file'],
        ['name' => 'platform/file/index', 'p' => 'file'],
        ['name' => 'platform/question/keywords-choose', 'p' => 'searchQuestion'],
        ['name' => 'platform/question/chapter-choose', 'p' => 'chapterQuestion'],
        ['name' => 'platform/question/knowledge-choose', 'p' => 'knowledgeQuestion'],
        ['name' => 'basket/index', 'p' => 'setQuestion'],
        ['name' => 'platform/answer/index', 'p' => 'platformAnswer'],
        ['name' => 'class/homework', 'p' => 'teacherHomework'],
        ['name' => 'class/work-details', 'p' => 'teacherPiGai'],
        ['name' => 'teacher/setting/personal-center', 'p' => 'teacherCenter'],
        ['name' => 'teacher/message/msg-contact', 'p' => 'teacherNotice'],
        ['name' => 'teacher/message/notice', 'p' => 'teacherMessage'],
        ['name' => 'teacher/managetask/work-manage', 'p' => 'teacherAssignHomework'],
        ['name' => 'teacher/managepaper/index', 'p' => 'teacherManagepaper'],
        ['name' => 'teacher/answer/answer-questions', 'p' => 'teacherAnswerQuestion'],
        ['name' => 'workstatistical/work-statistical-all', 'p' => 'teacherAnalysis'],
        ['name' => 'workstatistical/work-statistical-topic', 'p' => 'teacherQuestionAnalysis'],
        ['name' => 'workstatistical/work-statistical-student', 'p' => 'teacherStudentAnalysis'],
        ['name' => 'class/class-file', 'p' => 'classFile'],
        ['name' => 'class/memorabilia', 'p' => 'classMemorabilia'],
        ['name' => 'class/memorabilia-album', 'p' => 'classMemorabiliaAlbum'],
        ['name' => 'class/add-memorabilia', 'p' => 'classAddMemorabilia'],
        ['name' => 'class/answer-questions', 'p' => 'classAnswer'],
        ['name' => 'class/student-homework', 'p' => 'studentHomework'],
        ['name' => 'classes/managetask/details', 'p' => 'studentAnswerHomework'],
        ['name' => 'student/setting/my-center', 'p' => 'studentCenter'],
        ['name' => 'student/message/notice', 'p' => 'studentNotice'],
        ['name' => 'student/message/sys-msg', 'p' => 'studentMessage'],
        ['name' => 'student/managetask/work-manage', 'p' => 'studentManagement'],
        ['name' => 'student/wrongtopic/manage', 'p' => 'studentWrongQuestion'],
        ['name' => 'student/answer/answer-questions', 'p' => 'studentAnswerQuestion'],

    ],
    'weixin_auth' => 'https://wx.banhai.com',
    //资源cdn
    'resCdn' => [
        '//c02.banhai.com'
    ],
];

